// UI language is separate from the market, currency, and provider taxonomy.
const STRINGS = {
 appName:['وفّر','Waffer'], tagline:['افحص عرض صيانة سيارتك قبل أن تدفع','Check your repair estimate before you pay'],
 marketLabel:['السوق التجريبي: السعودية • SAR','Pilot market: Saudi Arabia • SAR'],
 heroTitle:['هل عرض الورشة واضح ومعقول؟','Is your workshop estimate clear?'],
 heroLead:['ارفع عرض الصيانة لفهم بنوده والمعلومات الناقصة وأدلة مطابقة القطع. النتائج تحتاج مراجعتك قبل الموافقة.','Upload a repair estimate to review its line items, missing information, and catalog evidence. Review the results before approval.'],
 upload:['ارفع صورة العرض أو ملف PDF','Upload an estimate image or PDF'],
 uploadHint:['JPG / PNG / WEBP / PDF — حتى 3 MiB للملف، قبل ترميز الإرسال.','JPG / PNG / WEBP / PDF — up to 3 MiB before transport encoding.'],
 make:['الشركة','Make'], model:['الموديل','Model'], year:['سنة الصنع','Model year'], vinOptional:['رقم الهيكل VIN (اختياري)','VIN (optional)'],
 analyze:['حلّل عرضي','Analyze my estimate'], analyzing:['جارٍ التحليل…','Analyzing…'], checkVin:['تحقق من VIN','Check VIN'], retryMakes:['إعادة تحميل الشركات','Retry makes'], chooseVehicle:['اختر فئة السيارة الصحيحة من مرشحات الكتالوج','Select the correct catalog vehicle variant'], chooseMake:['اختر الشركة','Select make'], chooseCandidate:['اختر الفئة — لا يتم اختيارها تلقائيًا','Select a variant — no automatic selection'],
 privacy:['يرسل الملف إلى الخادم ومزود التحليل عند الضغط على «حلّل عرضي». لا تضف بيانات شخصية غير لازمة. لا يحفظ هذا الإصدار سجلًا للتحليلات في قاعدة بيانات.','The file is sent to the server and analysis provider when you select Analyze. Remove unnecessary personal details. This version has no database-backed analysis history.'],
 loadingTitle:['جارٍ تحليل عرضك','Analyzing your estimate'], stageVin:['التحقق من مرشحات السيارة','Checking vehicle candidates'], stageFile:['قراءة الملف المختار','Reading the selected file'], stageAnalysis:['انتظار استجابة تحليل المستند','Waiting for document analysis'], progressNote:['تعكس هذه الحالة الخطوة الجارية، وليست تأكيدًا لصحة البيانات المستخرجة.','This shows the current operation, not a guarantee that extracted data is correct.'], elapsed:['الوقت المنقضي','Elapsed'], cancel:['إلغاء العملية','Cancel'], cancelled:['أُلغيت العملية. قد يكون طلب مزود الخدمة قد بدأ بالفعل.','Cancelled. A provider request may already have started.'],
 resultTitle:['نتيجة التحليل','Analysis result'], totalShown:['الإجمالي المطبوع المستخرج من العرض','Extracted printed total'], calculated:['مجموع البنود كما أعاده التحليل — يحتاج مراجعة','Line-item sum returned by analysis — review required'], tax:['الضريبة المطبوعة','Printed tax'], labor:['أجور العمل المطبوعة','Printed labor total'], warranty:['الضمان المذكور','Stated warranty'], currencyContext:['عملة سياق التحليل، وليست تأكيدًا لعملة المستند','Analysis-context currency, not confirmation of document currency'],
 transparency:['شفافية العرض','Estimate transparency'], identity:['ثقة هوية القطع','Part identity confidence'], compatibility:['ثقة التوافق','Compatibility confidence'], priceConfidence:['قابلية مقارنة السعر','Price comparability'], scoreNote:['هذه الدرجات مخرجات أولية للتحليل، وليست احتمالات معايرة أو تقييمًا للورشة أو إثباتًا للتوافق.','These are preliminary analysis scores, not calibrated probabilities, a workshop rating, or proof of fitment.'],
 findings:['أبرز الملاحظات','Key findings'], noFindings:['لم تُستخرج ملاحظات إضافية؛ هذا لا يثبت اكتمال العرض.','No additional issues were extracted; this does not prove the estimate is complete.'],
 details:['عرض تفاصيل البنود','View line-item details'], editInput:['العودة للمدخلات','Back to inputs'], advancedTitle:['تفاصيل العرض والكتالوج','Estimate and catalog details'], detailsTitle:['بنود العرض المستخرجة','Extracted estimate line items'], lineItem:['البند','Line item'], itemType:['النوع','Type'], partNumber:['رقم القطعة','Part number'], price:['السعر المطبوع','Printed price'], priceAssessment:['تقييم قابلية المقارنة','Comparability assessment'], conflict:['التداخل المحتمل','Potential overlap'],
 part:['قطعة','Part'], service:['خدمة','Service'], fee:['رسوم','Fee'], laborType:['أجرة عمل','Labor'], unknown:['غير محدد','Unknown'], notShown:['غير ظاهر','Not shown'], noItems:['لم تُستخرج بنود واضحة.','No clear line items were extracted.'],
 catalogMatch:['مطابقة كتالوج القطع','Parts catalog matching'], candidateNote:['حتى 3 مرشحات متنوعة لكل بند. تشابه اسم الفئة لا يثبت توافق رقم القطعة أو أصالتها. يجب مراجعة الفئة والمحرك والموضع والمقاسات مع المورد.','Up to 3 diverse candidates per line. Category-name similarity does not prove exact fitment or OEM status. Verify variant, engine, position, and dimensions with the supplier.'],
 catalogWaiting:['جارٍ البحث في الكتالوج؛ يمكنك قراءة تحليل العرض الآن.','Searching the catalog; the estimate analysis is already available.'], catalogNone:['لم يبدأ بحث الكتالوج لعدم اختيار سيارة محددة من VIN.','Catalog lookup was not started: no specific VIN vehicle was selected.'], catalogComplete:['اكتمل البحث عن فئات القطع، وليس التحقق النهائي من التوافق.','Category lookup completed; final fitment is not confirmed.'], catalogFailed:['تعذر إكمال بحث الكتالوج؛ تحليل العرض ما زال متاحًا.','Catalog lookup could not complete; the estimate analysis remains available.'], catalogPartial:['اكتمل جزء من البحث؛ بعض الطلبات أو معايير الموضع لم تتوفر.','Lookup is partial; some requests or position criteria were unavailable.'], catalogTimeout:['انتهت مهلة الكتالوج وأُلغيت طلباته المتبقية.','Catalog deadline reached; remaining requests were cancelled.'], catalogNA:['لا توجد بنود قطع تحتاج بحث الكتالوج.','There are no part lines requiring catalog lookup.'],
 categoryMatched:['بنود حُددت فئتها','Lines with a matched category'], candidateLines:['بنود لها مرشحات','Lines with candidates'], SKIPPED:['بند عمل أو خدمة؛ لا يُبحث كقطعة.','Non-part line; no part lookup performed.'], NO_CATEGORY_MATCH:['لم تُحدد فئة مناسبة.','No suitable category was identified.'], NO_ARTICLES:['لا توجد مرشحات في الاستجابة المستلمة.','No candidates in the received response.'], POSITION_AMBIGUOUS:['البند يجمع أمامي وخلفي؛ يلزم فصلهما.','Both front and rear are specified; split this line for verification.'], POSITION_UNVERIFIED:['لم يثبت الموضع المطلوب ضمن العينة المفحوصة.','Requested position was not established within the inspected sample.'], ERROR:['تعذر طلب بيانات هذا البند.','The data request for this line failed.'], TIMEOUT:['انتهت المهلة قبل اكتمال البند.','The deadline was reached before this line completed.'], CANCELLED:['أُلغي بحث هذا البند.','Lookup for this line was cancelled.'], CANDIDATES:['مرشحات تحتاج تحققًا','Candidates requiring verification'], PENDING:['قيد الانتظار','Pending'],
 supplier:['المصنع/العلامة حسب الكتالوج','Catalog supplier/brand'], category:['فئة القطعة المرشحة','Candidate category'], similarity:['تشابه اسم الفئة — ليس ثقة توافق','Category-name similarity — not fitment confidence'], front:['أمامي','Front'], rear:['خلفي','Rear'], positionEvidence:['بيانات الموضع تدعم','Position criteria support'], sample:['عدد القطع التي عادت لها معايير ضمن عينة لا تتجاوز 10','Articles with returned criteria in a sample of at most 10'],
 beforePay:['قبل أن تدفع','Before you pay'], confirmedSaving:['التوفير المؤكد: غير محسوب','Confirmed savings: not calculated'], savingNote:['لا توجد مقارنة بأسعار سوق موثقة في هذه النسخة؛ لا نستنتج توفيرًا أو سعرًا عادلًا.','This version has no verified market-price comparison; no savings or fair-price conclusion is inferred.'],
 workshopButton:['إنشاء رسالة للورشة','Create a workshop message'], workshopFollowup:['رسالة استكمال للورشة','Workshop follow-up message'], workshopMessageTitle:['رسالة للورشة','Message to workshop'], messageReview:['راجع النص قبل مشاركته؛ لا يتضمن رقم VIN تلقائيًا.','Review before sharing; the VIN is not included automatically.'], messageFallback:['السلام عليكم، أرجو تأكيد أرقام القطع والمصنع والكميات وأجرة العمل والضمان قبل اعتماد العرض.','Please confirm part numbers, manufacturers, quantities, labor charges, and warranty before approval.'], copyMessage:['نسخ الرسالة','Copy message'], resultBack:['العودة للنتيجة','Back to result'], shareSummary:['مشاركة ملخص النتيجة','Share result summary'], copied:['تم نسخ النص.','Text copied.'], copyFailed:['تعذر النسخ التلقائي؛ حدد النص الظاهر وانسخه يدويًا.','Automatic copying failed; select the visible text and copy it manually.'], shareFailed:['تعذرت المشاركة؛ يمكنك استخدام رسالة الورشة ونسخها.','Sharing failed; use the workshop message and copy it.'], back:['رجوع','Back'], newAnalysis:['تحليل عرض آخر','Analyze another estimate'], diagnostics:['تفاصيل تقنية للاختبار — ليست شهادة دقة','Technical diagnostics — not an accuracy certificate'],
 vehicleUnverified:['لم تُحدد سيارة كتالوج بشكل موثوق لهذه العملية.','No unambiguous catalog vehicle was selected for this run.'], vehicleSelected:['سيارة الكتالوج المحددة لهذه العملية','Catalog vehicle selected for this run'], vinLoading:['جارٍ التحقق من VIN…','Checking VIN…'], vinNone:['لم تُرجع الخدمة سيارة كتالوج محددة. يمكن تحليل العرض دون مطابقة القطع.','No catalog vehicle was returned. Estimate analysis can continue without catalog matching.'], vinAmbiguous:['أعاد VIN عدة فئات. اختر الفئة الصحيحة؛ لن نعتمد أول نتيجة تلقائيًا.','VIN returned multiple variants. Select the correct one; the first result is not chosen automatically.'], vinFailed:['تعذر تحديد السيارة. يمكن تحليل العرض دون مطابقة الكتالوج.','Vehicle lookup failed. Estimate analysis can continue without catalog matching.'], manualChanged:['تغيّرت بيانات السيارة يدويًا؛ أعد فحص VIN لتفعيل مطابقة الكتالوج.','Vehicle details were edited; check VIN again to enable catalog matching.'],
 healthConfig:['أبلغ الخادم عن وجود إعدادات الخدمات؛ هذا لا يثبت نجاح تحليل مستند فعلي.','Server reports service configuration; this does not prove a live document analysis succeeds.'], healthPartial:['الخادم أبلغ عن خدمة غير جاهزة أو محدودة.','Server reports a service is unavailable or limited.'], healthUnknown:['تعذر قراءة حالة الخادم.','Server status could not be read.'], offline:['لا يوجد اتصال بالإنترنت. التحليل والكتالوج يحتاجان اتصالًا.','You are offline. Analysis and catalog lookup require internet access.'],
 install:['إضافة وفّر إلى الشاشة الرئيسية','Add Waffer to home screen'], updateApp:['تحديث نسخة الواجهة','Update application'],
 FILE_REQUIRED:['اختر صورة أو PDF أولًا.','Select an image or PDF first.'], FILE_EMPTY:['الملف فارغ أو لا يمكن قراءة حجمه.','The file is empty or its size is unavailable.'], FILE_TOO_LARGE:['الحد الحالي 3 MiB قبل الإرسال؛ صغّر الملف ثم أعد اختياره.','Current limit: 3 MiB before encoding. Reduce the file and select it again.'], FILE_TYPE:['نوع الملف غير مدعوم. استخدم JPG أو PNG أو WEBP أو PDF.','Unsupported type. Use JPG, PNG, WEBP, or PDF.'], FILE_READ:['تعذر قراءة الملف.','The file could not be read.'], YEAR_INVALID:['تحقق من سنة الصنع.','Check the model year.'], VIN_INVALID:['يجب أن يتكون VIN من 17 حرفًا/رقمًا صالحًا دون I أو O أو Q.','VIN must contain 17 valid characters without I, O, or Q.'], TIMEOUT:['انتهت مهلة الطلب. يمكنك المحاولة مرة أخرى.','Request timed out. You can try again.'], INVALID_RESPONSE:['وصلت استجابة غير صالحة من الخادم.','The server returned an invalid response.'], INVALID_ANALYSIS:['نتيجة التحليل ناقصة أو غير صالحة؛ لم تُعرض كتحليل ناجح.','Analysis output is incomplete or invalid; it was not shown as successful.'], REQUEST_FAILED:['تعذر إكمال الطلب. حاول لاحقًا.','The request could not complete. Try later.'], RATE_LIMITED:['الخدمة حدّت الطلبات مؤقتًا. انتظر قليلًا.','The service temporarily limited requests. Please wait.'], UNSUPPORTED_MARKET:['هذا السوق غير مدعوم حاليًا.','This market is not supported yet.']
};
const ALIASES = { ANALYSIS_TIMEOUT:'TIMEOUT', ANALYSIS_RATE_LIMITED:'RATE_LIMITED', ANALYSIS_UPSTREAM_INVALID:'INVALID_RESPONSE', ANALYSIS_UPSTREAM_ERROR:'REQUEST_FAILED', ANALYSIS_FAILED:'REQUEST_FAILED', CATALOG_INVALID_RESPONSE:'INVALID_RESPONSE', CATALOG_UPSTREAM_ERROR:'REQUEST_FAILED' };
export function t(locale, key) {
  const pair = STRINGS[ALIASES[key] || key];
  return pair ? pair[locale === 'en-SA' ? 1 : 0] : key;
}
